# Configuration Drift Reports
# See also: artifact_descriptions/configuration-drift-reports.md for complete guidance

# The Configuration Drift Reports artifact defines automated detection of infrastructure configuration drift from Infrastructure as Code (IaC) definitions using tools like Terraform drift detection, Clo...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact defines automated infrastructure drift detection, compliance policy scanning, and remediation workflows for IaC-managed infrastructure. It establishes drift detection schedules (hourly, daily), compliance policies (CIS benchmarks, custom OPA policies), reporting formats, and automated 

# BEST PRACTICES
# - Daily Drift Detection: Run terraform plan daily in CI/CD; alert on any detected drift for immediate investigation
# - Block Console Access: Restrict AWS console, Azure portal access to read-only; enforce infrastructure changes only through 
# - Automated Remediation: Auto-apply Terraform to correct benign drift; require approval for security-impacting changes
# - Policy-as-Code: Define security policies in OPA, Sentinel, AWS Config Rules; enforce at plan-time before apply
# - CIS Compliance: Scan IaC with Checkov, tfsec against CIS benchmarks; block non-compliant infrastructure in CI/CD

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Terraform drift detection"
      - "AWS CloudFormation drift detection"
      - "Pulumi refresh"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
