# Deployment Plan
# See also: artifact_descriptions/deployment-plan.md for complete guidance

# The Deployment Plan defines the strategy, procedures, and infrastructure for safely releasing software to production environments with minimal downtime and risk. Leveraging modern deployment patterns ...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# The Deployment Plan defines how software moves from code commit to production, including build processes, environment promotion, deployment patterns, rollback procedures, and success validation. It ensures deployments are automated, repeatable, auditable, and safe through progressive delivery techni

# BEST PRACTICES
# - Version Control: Store in centralized version control system (Git, SharePoint with versioning, etc.) to maintain comp
# - Naming Conventions: Follow organization's document naming standards for consistency and discoverability
# - Template Usage: Use approved templates to ensure completeness and consistency across teams
# - Peer Review: Have at least one qualified peer review before submitting for approval
# - Metadata Completion: Fully complete all metadata fields to enable search, classification, and lifecycle management

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Deployment patterns"
      - "CI/CD pipeline"
      - "Infrastructure as Code"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
