#!/usr/bin/env python3
"""
Generate all 391 artifact templates from descriptions using industry best practices.
"""
import os
import re
from pathlib import Path

# Mapping of artifact names to categories based on their nature
CATEGORY_MAPPING = {
    # AI/ML
    'ai-ethics-and-bias-assessment': 'ai-ml',
    'ai-use-case-inventory': 'ai-ml',
    'bias-and-fairness-reports': 'ai-ml',
    'explainability-reports': 'ai-ml',
    'genai-safety-evaluations': 'ai-ml',
    'model-cards': 'ai-ml',
    'model-governance-policy': 'ai-ml',
    'model-registry-entries': 'ai-ml',
    'model-risk-assessments': 'ai-ml',
    'experiment-tracking-logs': 'ai-ml',
    'hyperparameter-configurations': 'ai-ml',
    'training-data-cards': 'ai-ml',
    'evaluation-protocols': 'ai-ml',
    'safety-filter-configurations': 'ai-ml',
    'prompt-engineering-policy': 'ai-ml',

    # Architecture
    'architecture-overview': 'architecture',
    'architecture-vision': 'architecture',
    'architecture-approvals': 'architecture',
    'architecture-review-board-minutes': 'architecture',
    'architecture-waivers': 'architecture',
    'bounded-context-map': 'architecture',
    'capability-model': 'architecture',
    'class-diagrams': 'architecture',
    'component-diagrams': 'architecture',
    'component-model': 'architecture',
    'context-diagrams': 'architecture',
    'deployment-diagram': 'architecture',
    'deployment-topology-diagram': 'architecture',
    'domain-model': 'architecture',
    'er-diagrams': 'architecture',
    'logical-architecture-diagram': 'architecture',
    'network-topology-diagram': 'architecture',
    'physical-architecture-diagram': 'architecture',
    'reference-architectures': 'architecture',
    'security-architecture-diagram': 'architecture',
    'sequence-diagrams': 'architecture',
    'service-decomposition': 'architecture',
    'service-dependency-graph': 'architecture',
    'target-state-evolution-map': 'architecture',
    'team-topology-map': 'architecture',
    'use-case-diagrams': 'architecture',
    'data-flow-diagrams': 'architecture',
    'interface-control-document': 'architecture',
    'cloud-landing-zone-design': 'architecture',
    'zero-trust-design': 'architecture',
    'encryption-and-key-management-design': 'architecture',
    'iam-design': 'architecture',
    'monitoring-and-observability-design': 'architecture',
    'multi-region-active-active-plan': 'architecture',
    'caching-strategy': 'architecture',
    'caching-tiers': 'architecture',
    'configuration-design': 'architecture',
    'pipeline-architecture-diagram': 'architecture',

    # Compliance
    'acceptable-use-policy': 'compliance',
    'access-recertification-plan': 'compliance',
    'access-review-logs': 'compliance',
    'audit-readiness-workbook': 'compliance',
    'business-associate-agreement': 'compliance',
    'certificate-policy': 'compliance',
    'consent-models': 'compliance',
    'consent-receipts': 'compliance',
    'cookie-policy': 'compliance',
    'cookie-policy-inventory': 'compliance',
    'data-map': 'compliance',
    'data-processing-addendum': 'compliance',
    'data-protection-impact-assessment': 'compliance',
    'dsar-playbooks': 'compliance',
    'iso-27001-mapping': 'compliance',
    'privacy-impact-assessment': 'compliance',
    'privacy-labels': 'compliance',
    'privacy-policy': 'compliance',
    'records-of-processing-activities': 'compliance',
    'soc-2-control-implementation-matrix': 'compliance',
    'standard-contractual-clauses': 'compliance',
    'control-test-evidence-packs': 'compliance',
    'regulatory-mapping': 'compliance',
    'approval-evidence': 'compliance',
    'legal-hold-procedures': 'compliance',
    'exception-log': 'compliance',
    'exception-register': 'compliance',
    'archival-plan': 'compliance',
    'data-export-procedures': 'compliance',
    'customer-data-return-procedures': 'compliance',
    'eccn-classification': 'compliance',
    'export-control-screening': 'compliance',
    'terms-of-service': 'compliance',

    # Data
    'analytics-model-documentation': 'data',
    'data-contracts': 'data',
    'data-dictionaries': 'data',
    'data-freshness-slas': 'data',
    'data-lineage-maps': 'data',
    'data-lineage-tracking': 'data',
    'data-product-specification': 'data',
    'data-quality-rules': 'data',
    'data-residency-plan': 'data',
    'data-retention-plan': 'data',
    'database-schema-ddl': 'data',
    'dataset-documentation': 'data',
    'enterprise-data-model': 'data',
    'etl-elt-specifications': 'data',
    'event-schemas': 'data',
    'graphql-schema': 'data',
    'logical-data-model': 'data',
    'metadata-catalogs': 'data',
    'physical-data-model': 'data',
    'telemetry-schema': 'data',
    'dag-definitions': 'data',
    'great-expectations-suites': 'data',
    'feature-store-contracts': 'data',
    'reverse-etl-playbooks': 'data',
    'sync-contracts': 'data',
    'semantic-layer-definitions': 'data',
    'topic-and-queue-catalog': 'data',
    'retention-schedule': 'data',
    'schema-evolution-policy': 'data',
    'tenancy-and-isolation-model': 'data',

    # Deployment
    'build-scripts': 'deployment',
    'ci-cd-pipeline-definitions': 'deployment',
    'deployment-plan': 'deployment',
    'docker-compose-manifests': 'deployment',
    'dockerfiles': 'deployment',
    'helm-charts': 'deployment',
    'kustomize-manifests': 'deployment',
    'pipeline-definitions': 'deployment',
    'rollback-plan': 'deployment',
    'release-plan': 'deployment',
    'release-notes': 'deployment',
    'changelogs': 'deployment',
    'change-log': 'deployment',
    'version-tags': 'deployment',
    'release-certification': 'deployment',
    'release-risk-assessment': 'deployment',
    'cutover-checklist': 'deployment',
    'environment-matrix': 'deployment',
    'environment-promotion-rules': 'deployment',
    'promotion-rules': 'deployment',
    'promotion-workflows': 'deployment',
    'feature-flag-registry': 'deployment',
    'feature-rollback-playbooks': 'deployment',
    'installer-manifests': 'deployment',
    'grpc-proto-files': 'deployment',
    'migration-scripts': 'deployment',
    'iac-module-registry': 'deployment',

    # Documentation
    'admin-guides': 'documentation',
    'adr-index': 'documentation',
    'api-catalogs': 'documentation',
    'api-versioning-policy': 'documentation',
    'asyncapi-specification': 'documentation',
    'attribution-files': 'documentation',
    'coding-standards-and-style-guides': 'documentation',
    'contributing-guide': 'documentation',
    'contributor-license-agreements': 'documentation',
    'decision-log': 'documentation',
    'deprecation-policy': 'documentation',
    'developer-handbook': 'documentation',
    'faq': 'documentation',
    'glossary-and-taxonomy-index': 'documentation',
    'golden-path-guide': 'documentation',
    'installation-guides': 'documentation',
    'knowledge-base-articles': 'documentation',
    'on-call-handbook': 'documentation',
    'onboarding-guide': 'documentation',
    'openapi-specification': 'documentation',
    'operations-manual': 'documentation',
    'patterns-and-anti-patterns-library': 'documentation',
    'readme': 'documentation',
    'upgrade-guides': 'documentation',
    'user-manuals': 'documentation',
    'troubleshooting-trees': 'documentation',
    'content-strategy': 'documentation',
    'microcopy-guides': 'documentation',
    'trademark-guidance': 'documentation',
    'platform-services-catalog': 'documentation',
    'technology-standards-catalog': 'documentation',

    # Governance
    'benefits-realization-plan': 'governance',
    'benefits-realization-report': 'governance',
    'business-case': 'governance',
    'business-process-models': 'governance',
    'business-rules-catalog': 'governance',
    'cab-approvals': 'governance',
    'capitalization-policy': 'governance',
    'change-control-plan': 'governance',
    'communication-plan': 'governance',
    'continuous-improvement-plan': 'governance',
    'decommissioning-plan': 'governance',
    'engagement-plan': 'governance',
    'epic-charter': 'governance',
    'escalation-matrix': 'governance',
    'feasibility-study': 'governance',
    'go-no-go-minutes': 'governance',
    'governance-charter': 'governance',
    'initiative-charter': 'governance',
    'kpi-framework': 'governance',
    'lessons-learned-document': 'governance',
    'okr-definitions': 'governance',
    'ownership-charters': 'governance',
    'portfolio-roadmap': 'governance',
    'post-implementation-review': 'governance',
    'post-mortem-report': 'governance',
    'program-increment-plan': 'governance',
    'raci-per-workstream': 'governance',
    'raid-log': 'governance',
    'resource-plan': 'governance',
    'risk-appetite-statement': 'governance',
    'roi-model': 'governance',
    'roi-tco-calculators': 'governance',
    'staffing-plan': 'governance',
    'stakeholder-map': 'governance',
    'steering-committee-minutes': 'governance',
    'mission-statement': 'governance',
    'vision-statement': 'governance',
    'enterprise-risk-register': 'governance',
    'skills-matrix': 'governance',
    'time-allocation-worksheets': 'governance',

    # Operations
    'alert-catalogs': 'operations',
    'backup-and-recovery-plan': 'operations',
    'backup-verification-logs': 'operations',
    'capacity-models': 'operations',
    'capacity-plan': 'operations',
    'chaos-engineering-experiments': 'operations',
    'circuit-breaker-configurations': 'operations',
    'configuration-drift-reports': 'operations',
    'disaster-recovery-runbooks': 'operations',
    'dr-test-reports': 'operations',
    'error-budget-policy': 'operations',
    'error-taxonomy': 'operations',
    'eviction-policies': 'operations',
    'firewall-rules': 'operations',
    'idempotency-and-replay-protection-policy': 'operations',
    'incident-management-plan': 'operations',
    'incident-reports': 'operations',
    'kill-switch-designs': 'operations',
    'load-balancer-configurations': 'operations',
    'load-profiles': 'operations',
    'logging-taxonomy': 'operations',
    'metric-catalog': 'operations',
    'monitoring-dashboards': 'operations',
    'network-policies': 'operations',
    'operational-acceptance-certificate': 'operations',
    'playbooks': 'operations',
    'rate-limiting-policy': 'operations',
    'root-cause-analyses': 'operations',
    'runbooks': 'operations',
    'scaling-policies': 'operations',
    'service-configuration-files': 'operations',
    'service-level-objectives': 'operations',
    'service-mesh-configurations': 'operations',
    'sla-slo-schedules': 'operations',
    'standard-operating-procedures': 'operations',
    'toil-reduction-plan': 'operations',
    'uptime-methodology': 'operations',
    'cdn-and-waf-configs': 'operations',
    'dns-configurations': 'operations',
    'cloud-cost-optimization-reports': 'operations',
    'cost-anomaly-alerts': 'operations',
    'cost-tagging-policy': 'operations',
    'finops-dashboards': 'operations',
    'showback-and-chargeback-reports': 'operations',
    'drift-detection-reports': 'operations',
    'scheduling-slas': 'operations',
    'carbon-footprint-analysis': 'operations',
    'sustainability-reports': 'operations',

    # Requirements
    'acceptance-criteria': 'requirements',
    'accessibility-audits': 'requirements',
    'accessibility-requirements': 'requirements',
    'app-store-metadata': 'requirements',
    'competitive-analysis': 'requirements',
    'functional-requirements-specification': 'requirements',
    'high-fidelity-mockups': 'requirements',
    'information-architecture': 'requirements',
    'interactive-prototypes': 'requirements',
    'localization-plan': 'requirements',
    'locale-files': 'requirements',
    'market-analysis': 'requirements',
    'non-functional-requirements-matrix': 'requirements',
    'performance-strategy': 'requirements',
    'positioning-documents': 'requirements',
    'pricing-and-packaging-strategy': 'requirements',
    'price-books': 'requirements',
    'product-launch-plan': 'requirements',
    'product-requirements-document': 'requirements',
    'product-strategy': 'requirements',
    'requirements-traceability-matrix': 'requirements',
    'solution-briefs': 'requirements',
    'storyboards': 'requirements',
    'system-requirements-specification': 'requirements',
    'use-case-models': 'requirements',
    'user-journeys': 'requirements',
    'user-stories': 'requirements',
    'wireframes': 'requirements',
    'battlecards': 'requirements',
    'customer-communication-templates': 'requirements',
    'customer-onboarding-plan': 'requirements',
    'demo-scripts': 'requirements',
    'discount-guardrails': 'requirements',
    'gtm-checklist': 'requirements',
    'messaging-frameworks': 'requirements',
    'sales-enablement-kits': 'requirements',
    'status-page-communication-templates': 'requirements',
    'pseudo-localization-reports': 'requirements',
    'labs-and-workshops': 'requirements',
    'training-curriculum': 'requirements',
    'certification-exams': 'requirements',
    'sprint-goals': 'requirements',
    'velocity-and-burndown-reports': 'requirements',

    # Security
    'adversary-emulation-documents': 'security',
    'baseline-hardening-guides': 'security',
    'bug-bounty-brief': 'security',
    'build-reproducibility-notes': 'security',
    'code-review-records': 'security',
    'code-signing-records': 'security',
    'cosign-signatures': 'security',
    'ddos-posture-assessments': 'security',
    'hsm-procedures': 'security',
    'joiner-mover-leaver-workflows': 'security',
    'key-ceremony-records': 'security',
    'notarization-records': 'security',
    'open-source-license-bom': 'security',
    'penetration-testing-report': 'security',
    'provenance-attestations': 'security',
    'provenance-chain-documentation': 'security',
    'purple-team-reports': 'security',
    'quarterly-access-reviews': 'security',
    'rbac-abac-matrix': 'security',
    'rbac-abac-policy': 'security',
    'red-team-reports': 'security',
    'red-teaming-reports': 'security',
    'remediation-tracker': 'security',
    'sbom-policy': 'security',
    'sbom-verification-reports': 'security',
    'secret-rotation-schedule': 'security',
    'secrets-management-policy': 'security',
    'secure-coding-checklist': 'security',
    'secure-coding-policy': 'security',
    'security-detections-catalog': 'security',
    'security-policy-library': 'security',
    'security-test-results': 'security',
    'sod-conflict-matrices': 'security',
    'sod-matrix': 'security',
    'software-bill-of-materials': 'security',
    'static-analysis-reports': 'security',
    'third-party-risk-assessments': 'security',
    'threat-model': 'security',
    'vulnerability-disclosure-policy': 'security',
    'vulnerability-management-plan': 'security',
    'artifact-registry-policies': 'security',
    'artifact-store-policies': 'security',
    'role-catalog': 'security',
    'auto-update-policies': 'security',
    'ip-register': 'security',
    'cmp-configurations': 'security',

    # Testing
    'automated-quality-gates': 'testing',
    'automated-test-scripts': 'testing',
    'code-coverage-reports': 'testing',
    'defect-log': 'testing',
    'load-test-report': 'testing',
    'performance-test-plan': 'testing',
    'performance-test-results': 'testing',
    'production-hygiene-checklist': 'testing',
    'regression-test-suite': 'testing',
    'test-case-specifications': 'testing',
    'test-data-specification': 'testing',
    'test-plan': 'testing',
    'test-strategy': 'testing',
    'uat-plan': 'testing',
    'uat-sign-off-document': 'testing',
    'crash-reporting-taxonomy': 'testing',
    'crash-triage-playbooks': 'testing',
    'state-diagrams': 'testing',
    'traceability-matrix': 'testing',
    'triage-rules': 'testing',
    'vpat-acr-results': 'testing',
    'shadow-canary-deployment-scorecards': 'testing',
    'reproducibility-checklists': 'testing',

    # Additional mappings
    'commit-logs': 'deployment',
    'dependency-graph': 'architecture',
    'onboarding-checklist': 'governance',
    'offboarding-checklist': 'governance',
    'pull-request-summaries': 'deployment',
    'source-code-repositories': 'deployment',
    'renewal-playbooks': 'governance',
    'qbr-templates': 'governance',
    'success-plan-templates': 'governance',
    'subprocessor-notifications': 'compliance',
    'trust-center-content-plan': 'compliance',
    'trust-center-evidence-summaries': 'compliance',
    'vendor-management-pack': 'governance',
    'vendor-scorecards': 'governance',
    'sig-questionnaires': 'compliance',
    'synthetic-data-generation-plan': 'data',
}

def get_artifact_list():
    """Get all artifact description files."""
    desc_dir = Path('/home/user/betty/artifact_descriptions')
    return sorted([f.stem for f in desc_dir.glob('*.md')])

def get_category(artifact_name):
    """Determine the category for an artifact."""
    return CATEGORY_MAPPING.get(artifact_name, 'documentation')  # Default to documentation

def get_format(artifact_name, description_content):
    """Determine if artifact should be YAML or MD based on its nature."""
    # YAML for structured data, configs, schemas, specifications
    yaml_indicators = [
        'schema', 'specification', 'policy', 'configuration', 'manifest',
        'definition', 'contract', 'sla', 'slo', 'matrix', 'catalog',
        'registry', 'model', 'dag', 'rule', 'assessment', 'inventory',
        'register', 'schedule', 'framework'
    ]

    # Check artifact name
    for indicator in yaml_indicators:
        if indicator in artifact_name:
            return 'yaml'

    # Default to markdown for documentation, plans, reports, guides
    return 'md'

def main():
    """Main processing function."""
    artifacts = get_artifact_list()
    print(f"Found {len(artifacts)} artifact descriptions to process")

    # Group by category
    by_category = {}
    for artifact in artifacts:
        category = get_category(artifact)
        if category not in by_category:
            by_category[category] = []
        by_category[category].append(artifact)

    print("\nArtifacts by category:")
    for category, items in sorted(by_category.items()):
        print(f"  {category}: {len(items)} artifacts")

    return by_category

if __name__ == '__main__':
    result = main()
