# Configuration Design
# See also: artifact_descriptions/configuration-design.md for complete guidance

# Configuration Design documents define application and infrastructure configuration strategies, including environment-specific settings, feature flags, secrets management, and configuration-as-code app...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact serves as the authoritative specification for how applications and infrastructure components are configured across environments (dev, staging, production). It defines configuration storage, retrieval, versioning, and deployment strategies while ensuring security, auditability, and envi

# BEST PRACTICES
# - Version Control: Store in centralized version control system (Git, SharePoint with versioning, etc.) to maintain comp
# - Naming Conventions: Follow organization's document naming standards for consistency and discoverability
# - Template Usage: Use approved templates to ensure completeness and consistency across teams
# - Peer Review: Have at least one qualified peer review before submitting for approval
# - Metadata Completion: Fully complete all metadata fields to enable search, classification, and lifecycle management

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Environment-specific configuration strategies (dev, test, staging, production)"
      - "Configuration storage mechanisms (environment variables, config files, remote co"
      - "Secrets management using HashiCorp Vault, AWS Secrets Manager, Azure Key Vault, "
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
