# Deployment Diagram
# See also: artifact_descriptions/deployment-diagram.md for complete guidance

# The Deployment Diagram (UML Deployment Diagram) illustrates the physical infrastructure topology showing how software artifacts are deployed onto hardware nodes, including servers, containers, virtual

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact documents runtime deployment architecture enabling infrastructure teams to provision environments, operations teams to understand system topology, and architects to design for high availability, disaster recovery, and scalability. It supports capacity planning, cost estimation, securit...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Environment-Specific Diagrams: Create separate diagrams for production, staging, QA environments; production may have multi-region 
# - Multi-AZ for HA: Deploy across multiple availability zones within region for high availability; show redundant compon
# - Cloud-Native Icons: Use official AWS, Azure, GCP icons for cloud services; maintain visual consistency with cloud provid
# - Node Specifications: Annotate nodes with instance types (t3.large), container specs (CPU: 2, Memory: 4Gi), or serverless 
# - Network Details: Document VPC/subnet CIDR blocks, security group rules, network ACLs, routing tables for complete net

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Infrastructure nodes"
      - "Deployment environments"
      - "Container orchestration"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
