# Deployment Diagram
# See also: artifact_descriptions/deployment-diagram.md for complete guidance

# The Deployment Diagram (UML Deployment Diagram) illustrates the physical infrastructure topology showing how software artifacts are deployed onto hardware nodes, including servers, containers, virtual...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact documents runtime deployment architecture enabling infrastructure teams to provision environments, operations teams to understand system topology, and architects to design for high availability, disaster recovery, and scalability. It supports capacity planning, cost estimation, securit

# BEST PRACTICES
# - Environment-Specific Diagrams: Create separate diagrams for production, staging, QA environments; production may have multi-region 
# - Multi-AZ for HA: Deploy across multiple availability zones within region for high availability; show redundant compon
# - Cloud-Native Icons: Use official AWS, Azure, GCP icons for cloud services; maintain visual consistency with cloud provid
# - Node Specifications: Annotate nodes with instance types (t3.large), container specs (CPU: 2, Memory: 4Gi), or serverless 
# - Network Details: Document VPC/subnet CIDR blocks, security group rules, network ACLs, routing tables for complete net

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Infrastructure nodes"
      - "Deployment environments"
      - "Container orchestration"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
