# Circuit Breaker Configurations
# See also: artifact_descriptions/circuit-breaker-configurations.md for complete guidance

# The Circuit Breaker Configurations document defines the resilience and fault tolerance settings for all service-to-service integrations, third-party API calls, and external system dependencies using c

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This document establishes the circuit breaker configurations for all service dependencies to prevent cascading failures, enable fast failure detection, and automate recovery during partial system outages. It solves the problem of how to fail gracefully when dependencies are unavailable by defining t...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Per-Dependency Configuration: Configure circuit breaker settings independently for each external dependency
# - SLO-Driven Thresholds: Derive failure thresholds from error budgets and SLO commitments (e.g., 99.9% SLO → 0.1% error thres
# - Volume Threshold: Set minimum request volume (e.g., 20 requests) before circuit evaluation to avoid false positives
# - Fast Failure: Configure open state to fail immediately without attempting calls (fail-fast principle)
# - Half-Open Testing: Use small number of test requests (3-5) in half-open state to probe recovery

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Circuit breaker libraries"
      - "Service mesh circuit breaking"
      - "API gateway circuit breaking"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
