# Cmp Configurations
# See also: artifact_descriptions/cmp-configurations.md for complete guidance

# The CMP Configurations artifact documents the technical and operational settings for Consent Management Platforms (CMPs) such as OneTrust, TrustArc, Cookiebot, Osano, and Usercentrics. This artifact e

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact documents the complete configuration specification for Consent Management Platform (CMP) deployments, ensuring privacy-compliant consent collection across all digital touchpoints. It serves as the authoritative reference for CMP technical settings, banner designs, purpose definitions, ...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Consent Banner Optimization: Design banners for minimal friction while maintaining compliance - avoid dark patterns, use clear la
# - A/B Testing for Consent Rates: Systematically test banner copy, button colors, positioning (bottom vs top), and interaction models 
# - Purpose Granularity: Configure specific, granular purposes rather than bundled consent - allow users to accept analytics 
# - Geo-Targeting Accuracy: Implement IP geolocation with 99%+ accuracy using MaxMind GeoIP2 or IP2Location to serve jurisdictio
# - IAB TCF 2.2 Compliance: Register as CMP with IAB, implement TC String v2.0 correctly, sync with Global Vendor List weekly, v

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "CMP platform configurations for OneTrust, TrustArc, Cookiebot, Osano, Usercentrics, Didomi, Sourcepoint, and Quantcast Choice"
      - "Consent banner design specifications including layout, copy, button styling, and mobile/desktop responsive behavior"
      - "IAB TCF 2.2 Global Vendor List (GVL) integration and vendor purpose mappings (Purposes 1-11, Special Purposes, Features, Special Features)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
