# Configuration Drift Reports
# See also: artifact_descriptions/configuration-drift-reports.md for complete guidance

# The Configuration Drift Reports artifact defines automated detection of infrastructure configuration drift from Infrastructure as Code (IaC) definitions using tools like Terraform drift detection, Clo

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact defines automated infrastructure drift detection, compliance policy scanning, and remediation workflows for IaC-managed infrastructure. It establishes drift detection schedules (hourly, daily), compliance policies (CIS benchmarks, custom OPA policies), reporting formats, and automated ...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Daily Drift Detection: Run terraform plan daily in CI/CD; alert on any detected drift for immediate investigation
# - Block Console Access: Restrict AWS console, Azure portal access to read-only; enforce infrastructure changes only through 
# - Automated Remediation: Auto-apply Terraform to correct benign drift; require approval for security-impacting changes
# - Policy-as-Code: Define security policies in OPA, Sentinel, AWS Config Rules; enforce at plan-time before apply
# - CIS Compliance: Scan IaC with Checkov, tfsec against CIS benchmarks; block non-compliant infrastructure in CI/CD

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Terraform drift detection"
      - "AWS CloudFormation drift detection"
      - "Pulumi refresh"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
