# Crash Triage Playbooks
# See also: artifact_descriptions/crash-triage-playbooks.md for complete guidance

# The Crash Triage Playbooks artifact provides standardized, repeatable procedures for rapidly diagnosing, categorizing, and responding to application crashes and system failures. These playbooks enable...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact serves as the definitive procedural guide for triaging application crashes and system failures with a security-first mindset, ensuring rapid classification, appropriate escalation, evidence preservation, and coordinated response while distinguishing between benign software defects and 

# BEST PRACTICES
# - Automated Detection Integration: Deploy crash detection across all monitoring platforms (APM, SIEM, logging aggregators) with automat
# - Security-First Mindset: Always evaluate crashes for security implications before treating as pure operational issues
# - Evidence Preservation: Immediately secure crash artifacts, memory dumps, and logs before any remediation activities
# - Standardized Classification: Use consistent severity and security risk classification across all crash types and systems
# - MITRE ATT&CK Mapping: Map crash characteristics to MITRE ATT&CK techniques to identify potential attack patterns

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Crash detection and initial classification procedures"
      - "Security-focused triage decision trees and criteria"
      - "Memory dump collection and analysis procedures"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
