# Dns Configurations
# See also: artifact_descriptions/dns-configurations.md for complete guidance

# DNS Configurations are the critical infrastructure artifacts that enable service discovery, load balancing, and automated certificate provisioning within cloud-native environments. Spanning from clust

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact defines DNS configurations for service discovery, external DNS management, and certificate automation within Kubernetes and cloud environments. It ensures applications are addressable via human-readable names, automatically provision TLS certificates, and maintain high-availability DNS...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - NodeLocal DNSCache: Deploy NodeLocal DNSCache to reduce DNS query latency and apiserver load
# - DNS-01 for Wildcards: Use DNS-01 ACME challenges for wildcard certificates instead of HTTP-01
# - external-dns Ownership: Configure external-dns with txt registry to prevent conflicts between multiple clusters
# - Separate DNS Zones: Use separate DNS zones for each environment (dev, staging, production) to prevent cross-environment 
# - Appropriate TTLs: Set short TTLs (30-60 seconds) for dynamic services, longer TTLs (300-3600 seconds) for static servi

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "CoreDNS configuration for in-cluster service discovery"
      - "CoreDNS custom domains, conditional forwarding, and stub domains"
      - "external-dns for automatic DNS record synchronization (Route 53, Azure DNS, Cloud DNS, Cloudflare)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
