# Dsar Playbooks
# See also: artifact_descriptions/dsar-playbooks.md for complete guidance

# The DSAR (Data Subject Access Request) Playbooks artifact documents standardized procedures for processing privacy requests under GDPR, CCPA, and other data protection regulations. This artifact speci...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact documents step-by-step procedures (playbooks) for processing data subject access requests (DSARs) under GDPR, CCPA, and other privacy regulations. It specifies request intake, identity verification, data discovery, request fulfillment, delivery, and documentation workflows to ensure co

# BEST PRACTICES
# - Automated Workflows: Use privacy automation platforms (OneTrust, TrustArc, BigID) to streamline intake, tracking, and ful
# - Identity Verification: Implement strong identity verification (MFA, ID validation) to prevent fraudulent requests and unaut
# - Centralized Tracking: Maintain single source of truth for all DSARs with status tracking, deadline monitoring, escalation 
# - Data Discovery Automation: Implement automated personal data discovery across systems, reduce manual searches, update data inve
# - Template Responses: Use standardized response templates for common scenarios, ensure legal review of templates, maintain

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "GDPR rights"
      - "CCPA rights"
      - "Request intake"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
