# Dsar Playbooks
# See also: artifact_descriptions/dsar-playbooks.md for complete guidance

# The DSAR (Data Subject Access Request) Playbooks artifact documents standardized procedures for processing privacy requests under GDPR, CCPA, and other data protection regulations. This artifact speci

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact documents step-by-step procedures (playbooks) for processing data subject access requests (DSARs) under GDPR, CCPA, and other privacy regulations. It specifies request intake, identity verification, data discovery, request fulfillment, delivery, and documentation workflows to ensure co...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Automated Workflows: Use privacy automation platforms (OneTrust, TrustArc, BigID) to streamline intake, tracking, and ful
# - Identity Verification: Implement strong identity verification (MFA, ID validation) to prevent fraudulent requests and unaut
# - Centralized Tracking: Maintain single source of truth for all DSARs with status tracking, deadline monitoring, escalation 
# - Data Discovery Automation: Implement automated personal data discovery across systems, reduce manual searches, update data inve
# - Template Responses: Use standardized response templates for common scenarios, ensure legal review of templates, maintain

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "GDPR rights"
      - "CCPA rights"
      - "Request intake"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
