# Environment Matrix
# See also: artifact_descriptions/environment-matrix.md for complete guidance

# The Environment Matrix is a comprehensive configuration framework that defines infrastructure, application, and operational parameters across all deployment environments (development, staging, product

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact defines the complete configuration matrix for all deployment environments, regions, clouds, and clusters, specifying infrastructure sizing, security policies, networking configurations, operational parameters, and compliance requirements. It serves as the single source of truth for und...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Environment Parity: Maintain structural consistency across environments while varying only size and scale
# - Production-Like Staging: Size staging environment close to production for accurate performance testing
# - Immutable Environments: Treat environments as immutable; recreate rather than patch for configuration changes
# - Progressive Promotion: Always promote changes through dev -> staging -> prod pipeline, never skip stages
# - Configuration as Code: Store all environment configurations in Git with version control and audit trails

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Environment definitions (dev, staging, UAT, pre-prod, production)"
      - "Region/availability zone configurations (us-east-1, eu-west-1, ap-southeast-1)"
      - "Cloud provider-specific settings (AWS, Azure, GCP, on-premises)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
