# Load Balancer Configurations
# See also: artifact_descriptions/load-balancer-configurations.md for complete guidance

# The Load Balancer Configurations artifact defines traffic distribution and high availability strategies for web applications, APIs, and microservices using cloud-native and self-hosted load balancing 

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact defines load balancer configurations to distribute traffic across multiple backend instances, achieve 99.95-99.99% availability through automated failover, enable zero-downtime deployments, optimize application performance through intelligent routing algorithms, and provide SSL/TLS ter...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Version Control: Store load balancer configurations as infrastructure-as-code (Terraform, CloudFormation) in Git
# - Layer 7 for HTTP: Use Application Load Balancers (ALB) or NGINX for HTTP/HTTPS traffic to enable path-based routing an
# - Layer 4 for TCP/UDP: Use Network Load Balancers (NLB) for ultra-low latency, high throughput, and static IP requirements
# - Multi-AZ Deployment: Enable cross-zone load balancing for high availability across multiple availability zones
# - Health Check Configuration: Configure aggressive health checks (5-10 second intervals) with appropriate thresholds (2 healthy, 2

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Cloud-native load balancers (AWS ALB, NLB, CLB, GWLB; Azure Load Balancer, Application Gateway; GCP Cloud Load Balancing)"
      - "Kubernetes ingress controllers (NGINX Ingress Controller, Traefik, HAProxy Ingress, AWS Load Balancer Controller)"
      - "Service mesh load balancing (Istio, Linkerd, Consul Connect, AWS App Mesh)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
