# Product Strategy
# See also: artifact_descriptions/product-strategy.md for complete guidance

# The Product Strategy is a foundational deliverable within the Inception / Strategy phase that defines the product vision, target market, competitive differentiation, value proposition, and strategic b...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact serves as the definitive strategic guide for product development, defining the product vision, target market segments, competitive differentiation, value proposition, and strategic initiatives. It answers critical questions: What problem are we solving? For whom? How do we win? What ar

# BEST PRACTICES
# - Version Control: Store in centralized version control system (Git, SharePoint with versioning, etc.) to maintain comp
# - Naming Conventions: Follow organization's document naming standards for consistency and discoverability
# - Template Usage: Use approved templates to ensure completeness and consistency across teams
# - Peer Review: Have at least one qualified peer review before submitting for approval
# - Metadata Completion: Fully complete all metadata fields to enable search, classification, and lifecycle management

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Product vision, mission, and strategic objectives"
      - "Target market definition and segmentation (TAM/SAM/SOM)"
      - "Value proposition and competitive differentiation"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
