# Production Hygiene Checklist
# See also: artifact_descriptions/production-hygiene-checklist.md for complete guidance

# The Production Hygiene Checklist is a comprehensive pre-deployment validation artifact that ensures production environments maintain operational excellence, security posture, monitoring coverage, runb

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# The production hygiene checklist validates operational readiness, infrastructure health, monitoring coverage, runbook completeness, security posture, and incident response preparedness before deployments and during regular operational reviews. It prevents production issues through proactive validati...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Regular Hygiene Reviews: Conduct production hygiene checks weekly or biweekly, not just before major releases
# - Automated Validation: Automate checklist validation where possible (monitoring coverage, backup success, certificate expir
# - SLI/SLO Tracking: Define and track service level indicators/objectives for all critical services
# - Monitoring Coverage Gaps: Identify and remediate monitoring blind spots before they cause incidents
# - Alert Tuning: Continuously tune alerts to reduce noise and prevent alert fatigue

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Monitoring and alerting validation (Prometheus, Grafana, Datadog, New Relic dashboards and alerts)"
      - "SLI/SLO/SLA tracking (service level indicators, objectives, error budgets, availability targets)"
      - "Logging and log aggregation (ELK Stack, Splunk, CloudWatch Logs, structured logging)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
