# Safety Filter Configurations
# See also: artifact_descriptions/safety-filter-configurations.md for complete guidance

# The Safety Filter Configurations artifact defines content moderation policies, toxicity thresholds, PII detection rules, and jailbreak prevention mechanisms for AI systems and user-generated content p...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact establishes comprehensive content safety configurations that filter harmful, toxic, or inappropriate content from AI system inputs and outputs, protect sensitive user information through PII detection, and prevent adversarial attacks through jailbreak detection. It defines the rules, t

# BEST PRACTICES
# - Start Conservative: Begin with strict thresholds (0.8-0.9) and relax based on false positive data, not vice versa
# - Multi-Layer Defense: Implement both input and output filtering; never rely on single layer
# - Monitor False Positives: Track and review false positive cases to tune thresholds appropriately
# - Context-Aware Filtering: Adjust thresholds based on context (public vs. private, user demographics)
# - Fail Safe: On API failures, default to safe behavior (block on uncertainty or defer to human review)

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Content moderation policies and toxicity thresholds"
      - "Perspective API configuration (toxicity, severe toxicity, identity attack, profa"
      - "Azure Content Safety severity levels and categories"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
