# Service Configuration Files
# See also: artifact_descriptions/service-configuration-files.md for complete guidance

# Service Configuration Files are the foundational artifacts that define runtime behavior, environment-specific settings, and operational parameters for cloud-native applications. Primarily manifested a

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact defines all configuration data required by applications and services at runtime, including environment variables, feature flags, database connection strings, API endpoints, resource limits, and sensitive credentials. It ensures configuration is externalized, versioned, and managed thro...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Never Commit Secrets: Never store unencrypted secrets in Git; use SOPS, sealed-secrets, or external secret references
# - Immutable ConfigMaps: Use immutable ConfigMaps to prevent accidental modifications and enable safe rollbacks
# - Least Privilege Access: Apply RBAC to restrict ConfigMap/Secret access to only authorized service accounts and users
# - Encryption at Rest: Enable Kubernetes etcd encryption and integrate with cloud KMS providers (AWS KMS, Azure Key Vault, 
# - Secret Rotation: Implement automated secret rotation with tools like External Secrets Operator and Vault

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Kubernetes ConfigMaps for non-sensitive application configuration"
      - "Kubernetes Secrets (with encryption at rest via KMS or etcd encryption)"
      - "External secret management (Vault, AWS Secrets Manager, Azure Key Vault, Google Secret Manager)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
# QUALITY CHECKLIST
# Before finalizing, verify:
# ✓ Completeness: All required sections present and adequately detailed
# ✓ Accuracy: Information verified and validated by appropriate subject matter experts
# ✓ Clarity: Written in clear, unambiguous language appropriate for intended audience
# ✓ Consistency: Aligns with organizational standards, templates, and related artifacts
# ✓ Currency: Based on current information; outdated content removed or updated

relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
