# Training Curriculum
# See also: artifact_descriptions/training-curriculum.md for complete guidance

# The Training Curriculum is a comprehensive security awareness and skills development artifact that establishes organization-wide training programs for compliance, security, and privacy education. Orga...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# This artifact provides the comprehensive framework for designing, delivering, tracking, and measuring security, compliance, and privacy training across the organization. The curriculum enables risk-based training delivery aligned with regulatory requirements, role responsibilities, and threat landsc

# BEST PRACTICES
# - Document Management: - **LMS Platform**: Deploy dedicated security awareness platform (KnowBe4, Proofpoint, Mimecast) vs.
# - Training Program Design: - **Risk-Based Approach**: Prioritize training based on role risk (Finance/HR: data protection, IT: 
# - Compliance Training Requirements: - **SOC 2 (CC1.4)**: Annual security awareness for all employees, role-based training for security/I
# - Phishing Simulation Programs: - **Quarterly Campaigns**: Run simulated phishing tests quarterly for all employees, monthly for hig
# - Role-Based Training Paths: - **All Employees**: Annual security awareness (60 min), privacy basics (30 min), acceptable use pol

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "Annual security awareness training for all employees (GDPR, PCI-DSS, HIPAA, SOC "
      - "Role-based technical training (Security Engineers, Developers, IT Operations, Co"
      - "Compliance-specific training (SOC 2, ISO 27001, PCI-DSS, GDPR, HIPAA, SOX)"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
