# Training Curriculum
# See also: artifact_descriptions/training-curriculum.md for complete guidance

# The Training Curriculum is a comprehensive security awareness and skills development artifact that establishes organization-wide training programs for compliance, security, and privacy education. Orga

metadata:
  # Document Control
  version: "1.0.0"  # Semantic versioning (MAJOR.MINOR.PATCH)
  created: "YYYY-MM-DD"  # Date this artifact was created
  lastModified: "YYYY-MM-DD"  # Date of most recent update
  status: "Draft"  # Draft | Review | Approved | Published | Deprecated

  # Ownership & Accountability
  author: "Author Name"  # Primary author of this artifact
  documentOwner: "Owner Role/Name"  # Person/role responsible for maintenance
  classification: "Internal"  # Public | Internal | Confidential | Restricted

  # Approvals
  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      approvalDate: null  # Date of approval (YYYY-MM-DD)

# PURPOSE
# This artifact provides the comprehensive framework for designing, delivering, tracking, and measuring security, compliance, and privacy training across the organization. The curriculum enables risk-based training delivery aligned with regulatory requirements, role responsibilities, and threat landsc...

# MAIN CONTENT
# Complete the sections below based on your specific artifact needs

# BEST PRACTICES:
# - Document Management: - **LMS Platform**: Deploy dedicated security awareness platform (KnowBe4, Proofpoint, Mimecast) vs.
# - Training Program Design: - **Risk-Based Approach**: Prioritize training based on role risk (Finance/HR: data protection, IT: 
# - Compliance Training Requirements: - **SOC 2 (CC1.4)**: Annual security awareness for all employees, role-based training for security/I
# - Phishing Simulation Programs: - **Quarterly Campaigns**: Run simulated phishing tests quarterly for all employees, monthly for hig
# - Role-Based Training Paths: - **All Employees**: Annual security awareness (60 min), privacy basics (30 min), acceptable use pol

content:
  overview: |
    # Provide a high-level overview of this artifact
    # What is this document about?
    # Why does it exist?
    
  scope:
    inScope:
      - "Annual security awareness training for all employees (GDPR, PCI-DSS, HIPAA, SOC 2 requirements)"
      - "Role-based technical training (Security Engineers, Developers, IT Operations, Compliance)"
      - "Compliance-specific training (SOC 2, ISO 27001, PCI-DSS, GDPR, HIPAA, SOX)"
      # Add additional in-scope items
    outOfScope:
      - "Item explicitly out of scope"
      # Add additional out-of-scope items

  details: |
    # Provide detailed information specific to this artifact type
    # Include all necessary technical details
    # Reference the artifact description for required sections
    
relatedDocuments:
  - type: "Related Artifact Type"
    path: "path/to/related/artifact"
    relationship: "depends-on | references | supersedes | implements"

changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
