# Openapi Specification
# See also: artifact_descriptions/openapi-specification.md for complete guidance

# The OpenAPI Specification (formerly Swagger) is a machine-readable, language-agnostic API contract that defines RESTful API endpoints, request/response schemas, authentication methods, and operation b...

metadata:
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastModified: "YYYY-MM-DD"
  status: "Draft"
  author: "Author Name"
  documentOwner: "Owner Name/Role"
  classification: "Internal"

  approvers:
    - name: "Approver Name"
      role: "Approver Role"
      date: null

# PURPOSE
# The OpenAPI Specification defines the complete API contract for RESTful APIs in machine-readable YAML or JSON format, documenting endpoints, HTTP methods, request/response schemas, authentication, parameters, error codes, and examples to enable automatic tooling, client generation, and interactive d

# BEST PRACTICES
# - Version Control: Store in centralized version control system (Git, SharePoint with versioning, etc.) to maintain comp
# - Naming Conventions: Follow organization's document naming standards for consistency and discoverability
# - Template Usage: Use approved templates to ensure completeness and consistency across teams
# - Peer Review: Have at least one qualified peer review before submitting for approval
# - Metadata Completion: Fully complete all metadata fields to enable search, classification, and lifecycle management

# Main content - customize based on artifact type
content:
  summary: |
    Provide overview and context for this artifact.
  
  scope:
    included:
      - "API metadata"
      - "Path definitions"
      - "Request specifications"
    
    excluded:
      - "Items explicitly out of scope"
  
# Related artifacts
relatedArtifacts:
  - type: "Related Artifact Type"
    path: "path/to/artifact"
    relationship: "depends-on | references | implements"

# Change history
changeHistory:
  - version: "1.0.0"
    date: "YYYY-MM-DD"
    author: "Author Name"
    changes: "Initial version"
